server:
  port: 8082
  servlet:
      context-path: /index
  tomcat:
    uri-encoding: UTF-8

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/student?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123

#解决数据库的'_'显示为空的问题
mybatis:
  configuration:
    map-underscore-to-camel-case: true
